---------------------------------------------------------------------------------------------------
----GENERAL CRAP
---------------------------------------------------------------------------------------------------
local appName = "mRadial"
local L = LibStub("AceLocale-3.0"):GetLocale(appName, false) or nil

ROOTICONPATH ="Interface/ICONS"
MR_MEDIAPATH = "Interface\\AddOns\\mRadial\\media"
MAINFRAME_ISMOVING = false
READYSTR = L["Opt_RDY_name"]
NOPOWER = L["Opt_NOPOWER_name"]
READYTEXT = L["Opt_RDY_name"]
OORTEXT = L["Opt_OOR_name"]

MR_GCD = 1.5 --w as 1.5
MR_INTERVAL = .1
DEFAULT_FRAMESIZE = 150
DEFAULT_RADIUS = 150

MR_DEFAULT_FONT = "Interface\\AddOns\\mRadial\\fonts\\HARRYP__.ttf"
MR_FONTS = {}
MR_FONTS[1] = "Accidental Presidency"
MR_FONTS[2] = "HARRYP__"
MR_FONTS[3] = "Nueva Std Cond"
MR_FONTS[4] = "Oswald-Regular"
MR_FONTS[5] = "Mochalatte-JRorB"
MR_FONTS[6] = "HoodBrothers-Yo9y"
MR_FONTS[7] = "DejaVuSansMono"
MR_FONTS[8] = "AnonymousPro-Bold"
MR_FONTS[9] = "MONOFONT"

MAINBG_FRAMENAME = "mRadialOutOfShardsFrame"
PRIMARY_FRAMENAME = "mRadialPrimaryFrame"
SECONDARY_FRAMENAME = "mRadialSecondaryFrame"
SHARD_FRAMENAME = "MWShardFrame"
IMPCOUNT_FRAMENAME = "MRImpFrame"
LINKEDSPELLS = {}

OFF_ALPHA = 0
DISABLED_ALPHA = .5
READY_ALPHA = 1

-- TABLE KEYS
MR_KEY_ASBUTTONS = "asbuttons"

-- Defaults
MR_CROSSHAIR_PATH = MR_MEDIAPATH .."\\crosshair.blp"

MR_DEFAULT_WATCHERFRAMESIZE = 34
MR_DEFAULT_TEXTURESIZE = 100
MR_DEFAULT_TEMPLATE = "BackdropTemplate"

MR_DEFAULT_RADIAL_MASK = "Interface/Artifacts/Artifacts-PerkRing-Final-Mask"
MR_DEFAULT_ICONSIZE = 25
MR_DEFAULT_BORDERALPHA = 1

MR_DEFAULT_AUTOSPREAD = true
MR_DEFAULT_ASBUTTONS = false
MR_DEFAULT_HIDESECONDARY = false
MR_DEFAULT_IMPCOUNTERFRAME = true
MR_DEFAULT_HIDEOOC = false
MR_DEFAULT_HIDEMINIMAP = true
MR_DEFAULT_RADIUSMULT = 1
MR_DEFAULT_FONTPERCENTAGE = .5
MR_DEFAULT_FONTSIZE = 2
MR_DEFAULT_FONTBIGGERSIZE = 9

MR_DEFAULT_OOS_FS = 100
MR_DEFAULT_HIDE_OOSF = false
MR_DEFAULT_SHARD_FS = 100
MR_DEFAULT_SHARD_HIDE = false
MR_DEFAULT_SHARD_TRANS = .5
MR_DEFAULT_IMP_HIDE = false

MR_DEFAULT_UDOFFSET = 0
MR_DEFAULT_LROFFSET = -15

MR_DEFAULT_CDUDOFFSET = 0
MR_DEFAULT_CDLROFFSET = 0

MR_DEFAULT_READYUDOFFSET = -17
MR_DEFAULT_READYLROFFSET = 0

MR_DEFAULT_COUNTUDOFFSET = 16
MR_DEFAULT_COUNTLROFFSET = -15

MR_DEFAULT_DEBUFFUDOFFSET = 0
MR_DEFAULT_DEBUFFLROFFSET = 0

MR_DEFAULT_POWERFLROFFSET = 0

MR_DEFAULT_POWERENABLED = true
MR_DEFAULT_POWERPERSISTS = true

MR_DEFAULT_POWERUDOFFSET = 5
MR_DEFAULT_POWERLROFFSET = 25

MR_DEFAULT_PET_FRAMESIZE = 45
MR_DEFAULT_PET_FONTSIZE = 2
MR_DEFAULT_PET_FONTBIGGERSIZE = 9
MR_DEFAULT_PET_UDOFFSET = 0
MR_DEFAULT_PET_LROFFSET = 10
MR_DEFAULT_PET_CDUDOFFSET = 0
MR_DEFAULT_PET_CDLROFFSET = 0
MR_DEFAULT_PET_READYUDOFFSET = -17
MR_DEFAULT_PET_READYLROFFSET = 0
MR_DEFAULT_PET_COUNTUDOFFSET = 16
MR_DEFAULT_PET_COUNTLROFFSET = -15
MR_DEFAULT_PET_WATCHERFRAMESIZE = 34
MR_DEFAULT_PET_DEBUFFUDOFFSET = 0
MR_DEFAULT_PET_DEBUFFLROFFSET = 0

MR_DEFAULT_RADIUS = 100
MR_DEFAULT_RADIUS2 = 180
MR_DEFAULT_SPREAD = 0.1
MR_DEFAULT_OFFSET = 1.4
MR_DEFAULT_WIDTH = 1
MR_DEFAULT_HEIGHT = 1

MR_DEFAULT_CENTERBELOW = true

SHADOWFURY_SPELLNAME = L["ShadowFurySpellname"]
SUMMONSOULKEEPER_SPELLNAME = L["SummonSoulKeeperSpellname"]

MR_DEFAULT_BUFFCOLOR = {.1, 1, .1, 1}
MR_DEFAULT_DEBUFFCOLOR = {.5, .5, .5, 1}
MR_DEFAULT_READYCOLOR = {.1, 1, .1, 1}
MR_DEFAULT_COUNTCOLOR = {0, 1, 1, 1}
MR_DEFAULT_CDCOLOR = {1, .1, .1, 1}
MR_DEFAULT_POWERCOLOR = {.3, .2, .5, 1}

MR_DEFAULT_NOPOWER = {.2, .2, .2, .75}
