-- Gather only the spells we're interested in! It's bit hard codey but I don't care atm...
--buffName, _, _, iconPath, parentSpellIcon, parentSpellName, skipBuff, isShardDependant
destro_specialisationData = {}
