-- function mRadial:COMPANION_UPDATE(eventName, arg1, arg2, arg3)
    -- this fires when anyone around you mounts, and there is no arg to check "player" NOT GREAT!
    -- print("eventName: %s", eventName)
    -- print("arg1: %s", arg1)
    -- print("arg2: %s", arg2)
    -- print("arg3: %s", arg3)
    -- if arg1 == "MOUNT" then
    --     mRadial:radialButtonLayout()
    -- end
-- end

-- mRadial:RegisterEvent("COMPANION_UPDATE")
